### ISSUE TITLE
SegFault in ocean_only mode when RESOLN_SCALED_KH = False

### ISSUE THREAD

**Issue by sditkovsky** [mom-ocean/MOM6#1464]
Issue Summary: 
(1) Warning needed for conflicts in variable mixing parameter allocation logic
(2) `RES_SCALE_MEKE_VISC` acts as `True` even when set to `False`

Hi all,

I was running into an issue in `ocean_only` mode where I was getting the following SegFault error:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
ocean_only         000000000163240D  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B7BF8C66630  Unknown               Unknown  Unknown
ocean_only         00000000008B9462  mom_hor_visc_mp_h         942  MOM_hor_visc.F90
ocean_only         0000000000750FF4  mom_dynamics_spli        1407  MOM_dynamics_split_RK2.F90
ocean_only         000000000102E15E  mom_mp_initialize        2613  MOM.F90
ocean_only         0000000000ECF859  MAIN__                    306  MOM_driver.F90
ocean_only         000000000040DFDE  Unknown               Unknown  Unknown
libc-2.17.so       00002B7BF9197555  __libc_start_main     Unknown  Unknown
ocean_only         000000000040DEE9  Unknown               Unknown  Unknown
```

The line in `MOM_hor_visc.F90` is:

 `942   if (CS%res_scale_MEKE) meke_res_fn = VarMix%Res_fn_h(i,j)`

Thus, `VarMix%Res_fn_h(i,j)` is called without being allocated. The allocation would be in `MOM_lateral_mixing_coeffs.F90`:

```
1383   if (CS%Resoln_scaled_Kh .or. CS%Resoln_scaled_KhTh .or. CS%Resoln_scaled_KhTr) then
   1384     CS%calculate_Rd_dx = .true.
   1385     CS%calculate_res_fns = .true.
   1386     allocate(CS%Res_fn_h(isd:ied,jsd:jed))       ; CS%Res_fn_h(:,:) = 0.0
   1387     allocate(CS%Res_fn_q(IsdB:IedB,JsdB:JedB))   ; CS%Res_fn_q(:,:) = 0.0
...
```

Indeed the issue is solved by setting any of `RESOLN_SCALED_KH`, `RESOLN_SCALED_KHTH`, `RESOLN_SCALED_KHTR` to `True` in the input file. **There should be a warning that one of these variables must be set if `RES_SCALE_MEKE_VISC = True`**.

However, I'm confused because I get this error even when `CS%res_scale_MEKE = .false.` (set by input param`RES_SCALE_MEKE_VISC`). **In debug mode**, the SegFault does not occur and I can confirm that `CS%res_scale_MEKE = .false.`. But with normal optimizations I get the SegFault. Does anyone know what could cause this to happen?

Thanks,

Sam Ditkovsky

**Comment by marshallward** [comment]
I think this code block is supposed to catch issues related to `VarMix%Res_fn_h` allocation:
https://github.com/NOAA-GFDL/MOM6/blob/e88cdaa785b9fab4e24286031bdd409caf673034/src/parameterizations/lateral/MOM_hor_visc.F90#L426-L433
Maybe the MEKE flag ought to be integrated into this block.

It's harder for me to comment on the other issue without a reproducibile test case, but it could be a vectorization problem similar to #1463.  Perhaps rewriting those blocks to remove `meke_res_fn` as proposed by @nikizadehgfdl will also resolve this issue?

If you are using GFDL mkmf templates and have not already done so, then you could try replacing `-msse2` with `-xsse2` in your template.  It may help.

**Comment by sditkovsky** [comment]
Thank you @marshallward. It does look like it might be the same issue as in #1463. And I am running on the Princeton cluster with a cluster-specific mkmf template, so that part is likely a compiler issue.
