### ISSUE TITLE
KPP nonlocal transport term not being applied to passive tracers

### ISSUE THREAD

**Issue by klindsay28** [mom-ocean/MOM6#1545]
`MOM_CVMix_KPP.F90` has subroutines `KPP_NonLocalTransport_temp` and `KPP_NonLocalTransport_saln` that compute and (conditionally) apply the nonlocal transport term of KPP to temperature and salinity respectively. There does not appear to be any analogue for passive tracers, for which the nonlocal term is proportional to the tracer surface flux.

We're working on a PR that computes and (conditionally) applies this term for passive tracers. We plan to submit the PR to the `dev/ncar` branch at https://github.com/NCAR/MOM6.

**Comment by mnlevy1981** [comment]
https://github.com/NCAR/MOM6/pull/202 is a draft PR that would address this issue on `dev/ncar`

**Comment by Hallberg-NOAA** [comment]
I believe that code that addresses this issue has now been merged into the main branch of MOM6, as one of the contributions from https://github.com/mom-ocean/MOM6/pull/1571, and that this issue can now be closed.
