### ISSUE TITLE
Bug in DOME2D temperature initialization in z and sigma coordinates

### ISSUE THREAD

**Issue by hdrake** [mom-ocean/MOM6#1560]
I don't think the following line serves any purpose and in fact inadvertently overwrites the temperature initialization from in the cases where `coordinateMode(verticalCoordinate) == REGRIDDING_SIGMA` or `coordinateMode(verticalCoordinate) == REGRIDDING_ZSTAR`

https://github.com/mom-ocean/MOM6/blob/399a7db1565e89e0ac8aeedd2de32bc846b1f230/src/user/DOME2d_initialization.F90#L335

**Comment by Hallberg-NOAA** [comment]
@hdrake, You are absolutely correct that this line is a bug, but the pull request that was supposed to have fixed it appears to have been closed, not merged, so this bug is still around.  Could you please put the corrective pull request in again to https://github.com/NOAA-GFDL/MOM6/pulls.  Thanks.

**Comment by Hallberg-NOAA** [comment]
This bug was corrected with https://github.com/NOAA-GFDL/MOM6/pull/165, which was merged into the main branch of MOM6 on 7/29/2022 as a part of https://github.com/mom-ocean/MOM6/pull/1577.
