### ISSUE TITLE
Field size error with on-grid temp-salt initialisation

### ISSUE THREAD

**Issue by angus-g** [mom-ocean/MOM6#1567]
When using `INIT_LAYERS_FROM_Z_FILE` with `TEMP_SALT_INIT_VERTICAL_REMAP_ONLY`, an error is raised when reading the field:

```
FATAL from PE     0: fms_io(read_data_3d_new), field thetao in file INPUT/ocean_daily_z_t0_theta.nc: field size mismatch 1
         131         179           1         131         179          75
```
It seems that the call to `MOM_read_data` doesn't match the `MOM_read_data_2d_region` interface, because `start` and `count` aren't passed through: https://github.com/mom-ocean/MOM6/blob/bac8031b662560066a950bd3c9849ea306abcc25/src/framework/MOM_horizontal_regridding.F90#L438-L440

**Comment by marshallward** [comment]
Can you check this in the dev/gfdl branch?  The main branch is currently using the older `field_size` implementation.

**Comment by angus-g** [comment]
Seems to reproduce on dev/gfdl too, this code doesn't use `field_size`. Looks more like it's trying to read the fields along _k_ but it's calling the wrong interface. Line 440 maybe should be:

```f90
call MOM_read_data(trim(filename), trim(varname), tr_in, start, count, G%domain)
```

**Comment by marshallward** [comment]
Sorry was just going by the title.  Did adding the arguments work?  If so, could you send a PR?

**Comment by angus-g** [comment]
Will do!
