### ISSUE TITLE
Verbosity level in `MOM_unique_scales.F90`

### ISSUE THREAD

**Issue by sanAkel** [mom-ocean/MOM6#1572]
When I have default `verbosity` i.e., `=2` My run goes through with no problem. 

However, when I have `verbosity = 3` or `> 3`, I get a crash in the initialization. Please see ⬇️. Also attached are:
- Log file (`log_file.txt`) [log_file.txt](https://github.com/mom-ocean/MOM6/files/8846564/log_file.txt)
- `MOM_parameter_doc.debugging` [MOM_parameter_doc.debugging.txt](https://github.com/mom-ocean/MOM6/files/8846554/MOM_parameter_doc.debugging.txt)
- `MOM_parameter_doc.all` [MOM_parameter_doc.all.txt](https://github.com/mom-ocean/MOM6/files/8846552/MOM_parameter_doc.all.txt)

>h-point: c=     88712 MOM_initialize_fixed: dF_dy
forrtl: severe (194): Run-Time Check Failure. The variable 'mom_unique_scales_mp_non_unique_scales_$NON_UNIQUE_SCALES' is being used in '/discover/nobackup/sakella/geosMom6/develop_06June2022/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/@GEOS_OceanGridComp/MOM6_GEOSPlug/@mom6/src/framework/MOM_unique_scales.F90(330,1)' without being defined
Image              PC                Routine            Line        Source
libmom6.so         00002AAAB6A7DDBD  mom_unique_scales         
330  MOM_unique_scales.F90
libmom6.so         00002AAAB6A6E9AE  mom_unique_scales          82  MOM_unique_scales.F90
libmom6.so         00002AAAB5813598  mom_check_scaling          56  MOM_check_scaling.F90
libmom6.so         00002AAAB5C840C1  mom_mp_initialize        2279  MOM.F90

**Comment by marshallward** [comment]
If I am reading the trace right, then the crash happens after exiting the `non_unique_scales` function.  Usually that means there was some corruption of the stack which was detected after leaving the function.

I haven't been able to replicate this in my simple tests, but will try to get something based on your parameter file running.

Also, it might help to know which compiler this came from, plus any flags if you can provide them.

**Comment by sanAkel** [comment]
> Also, it might help to know which compiler this came from, plus any flags if you can provide them.

`comp/intel/2021.3.0` and `mpi/impi/2021.3.0` and flags are at: https://github.com/GEOS-ESM/ESMA_cmake/blob/main/compiler/flags/Intel_Fortran.cmake

**Comment by sanAkel** [comment]
Diving deeper into the issue helped me reach following conclusion:

In the event that `nonzero_count <= 1` is satisfied at 
https://github.com/mom-ocean/MOM6/blob/e322186e6428594f07fbce4cc2e9028faf263c02/src/framework/MOM_unique_scales.F90#L279

non_unique_scales variable is **not** set, hence the [above](https://github.com/mom-ocean/MOM6/issues/1572#issue-1262182139) error.

**Comment by sanAkel** [comment]
https://github.com/NOAA-GFDL/MOM6/pull/142 closes this.
