### ISSUE TITLE
Interior mass source/sinks and non-local mixing

### ISSUE THREAD

**Issue by hdrake** [mom-ocean/MOM6#1574]
What is the best way to implement an interior mass source/sink, e.g. having an intake/discharge pipe at a certain depth? Our use case will be mass-conserving (we're just moving water around non-locally in vertical columns), but it would be nice to have a more general implementation that could be a net mass sink or source.

I imagine for a mass sink I only need to find reduce the layer thickness according to the rate of the mass (volume) sink? And sources would be treated the same way but, according to the various tracer concentrations of the source water, would additionally dilute the volume element's tracer content?

Is this as simple as editing [`applyTracerBoundaryFluxesInOut`
](https://github.com/mom-ocean/MOM6/blob/e322186e6428594f07fbce4cc2e9028faf263c02/src/tracer/MOM_tracer_diabatic.F90#L421) but allowing the mass source to the added at an arbitrary level rather than the top one?
https://github.com/mom-ocean/MOM6/blob/e322186e6428594f07fbce4cc2e9028faf263c02/src/tracer/MOM_tracer_diabatic.F90#L538

**Comment by adcroft** [comment]
Yes; removing mass would through a pipe only needs adjustment of the layer thickness, but adding mass should change the tracer concentrations. You first have to find the layer that spans the depth of the intake; see `find_eta()` in src/core/MOM_interface_heights.F90. I think `applyTracerBoundaryFluxesInOut` is the right place to do things for the tracers. The layer adjustment should probably happen in `applyBoundaryFluxesInOut`.

**Comment by adcroft** [comment]
Also, if you take out more volume than is in the layer, you need to iterate and find the next layer that spans the intake after adjusting the previous layer to zero. It just makes the algorithm a bit more fun.

**Comment by hdrake** [comment]
@Hallberg-NOAA, yes, thank you!
