### ISSUE TITLE
Spurious velocities in ice shelf cavities

### ISSUE THREAD

**Issue by claireyung** [mom-ocean/MOM6#1596]
Hi folks, I've got some MOM6 ice shelf cavities running, based on [the MOM6-examples ISOMIP examples](https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/gfdl/ocean_only/ISOMIP). With thermodynamics turned on it works quite nicely and gives nice melt patterns and circulations. However, when thermodynamics is turned off I still see quite large spurious velocities emerge in multiple types of vertical coordinates.

@Hallberg-NOAA suggested that the issue should be resolved by turning `KV_ML_INVZ2 = 0`, but unfortunately we still have quite large (order cm/s) velocities emerging in both the ISOMIP+ case and other configurations I have set up. See [this repo](https://github.com/claireyung/mom6-isomip-svtest) for configs and [this notebook](https://github.com/claireyung/mom6-isomip-svtest/blob/main/analysis/analysis_nb.ipynb) for some plots. 

Does anyone have any ideas about how to reduce these spurious velocities or what could be going wrong (either in this config or in the model)?

**Comment by marshallward** [comment]
Hi @claireyung apologies for the very long delay.  I have raised this with the group at GFDL in case anyone here has thoughts on it.  But I would also suggest that you post this question at the MOM6 forums, which is better suited for questions about model configuration and behavior.

https://bb.cgd.ucar.edu/cesm/forums/mom6.148/

I will close this issue for now, but please reach out to someone if you have not yet heard any feedback on this problem.
