### ISSUE TITLE
Bug in the implementation of NEMO equation of state

### ISSUE THREAD

**Issue by nikizadehgfdl** [mom-ocean/MOM6#405]
Bob pointed out that subroutine calculate_compress_nemo in MOM_EOS_NEMO.F90 calls 
gsw_rho_first_derivatives which calculates the derivative of rho wrt pressure, but using the TEOS-10
equation of state. This should be using the NEMO equation of state instead.

**Comment by nikizadehgfdl** [comment]
@StephenGriffies NEMO provides partial derivatives of density wrt T&S. But to calculate the compressibility we need the partial derivative wrt pressure which NEMO does not provide. Hence we are using the [ TEOS10 provided function as an approximation](https://github.com/NOAA-GFDL/MOM6/blob/dev/master/src/equation_of_state/MOM_EOS_NEMO.F90#L372) 

I will try to derive an expression using NEMO if they do not have one ready for use.

**Comment by StephenGriffies** [comment]
What is the status of this issue?

**Comment by StephenGriffies** [comment]
@nikizadehgfdl any update on this issue?

**Comment by Hallberg-NOAA** [comment]
This issue was addressed via https://github.com/NOAA-GFDL/MOM6/pull/331, which was merged onto the main branch of MOM6 on July 31, 2023.
